# csp network vpn client configuration (yaml format)

server:
  host: 206.0.29.4
  port: 8080

auth:
  client_id: test-client
  token: token123

protocol: udp
keepalive_interval: 30
connection_timeout: 10
auto_reconnect: true

log_level: info

# route all traffic through vpn (default route)
routes:
  - network: "0.0.0.0/0"
    gateway: "10.8.0.1"
