# csp network vpn client configuration (yaml format)

server:
  host: 127.0.0.1
  port: 8080

auth:
  client_id: my-laptop
  token: secret-auth-token-12345

protocol: udp
keepalive_interval: 30
connection_timeout: 10
auto_reconnect: true

log_level: info

# route all traffic through vpn (default route)
routes:
  - network: "0.0.0.0/0"
    gateway: "10.8.0.1"
