server:
  port: 1194
  interface: "::"
  protocol: "udp"
  threads: 4
  tunnel_mode: true

vpn:
  interface_name: "cspvpn-server"
  server_ip: "10.8.0.1"
  client_network: "10.8.0.0/24"
  ipv6_prefix: "2a0e:b107:1ef0::"
  mtu: 1280
  seed_file: "/etc/cspnetwork/seeds.dat"

seeded_ipv6:
  interface: "enp5s0"
  prefix: "2a0e:b107:1ef0::"
  seed_strategy: "per_domain"
  base_seed: "alakasan"
  rotation_interval: 3600

crypto:
  algorithm: "AES-256-GCM"
  key_derivation: "PBKDF2"
  iterations: 100000

network:
  tunnel_type: "tun"
  protocol: "udp"
  server_tun_interface: "cspvpn-server"
  routing_table: 200
  firewall_mark: 0x1000
  enable_forwarding: true

logging:
  level: "info"
  file: "/var/log/vpn/cspnetwork.log"
  max_size: "10MB"
  rotate: true

monitoring:
  enable_metrics: true
  metrics_port: 8081
  health_check_interval: 30

security:
  max_connections: 1000
  connection_timeout: 300
  rate_limit: 100
  enable_ddos_protection: true
